spring:
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/identity/**
          filters:
            - StripPrefix=2
        - id: learn-service
          uri: lb://LEARN-SERVICE
          predicates:
            - Path=/api/v1/learn/**
          filters:
            - StripPrefix=2
        - id: file-service
          uri: lb://FILE-SERVICE
          predicates:
            - Path=${app.api-prefix}/file/**
          filters:
            - StripPrefix=2
        - id: profile-service
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/api/v1/profile/**
          filters:
            - StripPrefix=2
server:
  port: 8222
  address: 0.0.0.0

app:
  api-prefix: /api/v1