spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/call_service_db?authSource=admin
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8083
  servlet:
    context-path: /call
