server:
  port: 8250
  servlet:
    context-path: /file
spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/file-service?authSource=admin
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  eureka:
    client:
      fetch-registry: true
app:
  file:
    storage-dir: F:/upload
    download-prefix: /file/media/download/
